apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: harmony
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        env:
        - name: GF_INSTALL_PLUGINS
          value: briangann-gauge-panel,grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource
        ports:
        - name: grafana
          containerPort: 3000
        resources:
          limits:
            memory: "8Gi"
            cpu: 4
          requests:
            memory: "1Gi"
            cpu: 1
        volumeMounts:
          - mountPath: /etc/grafana/provisioning/datasources/datasource.yaml
            name: grafana-config
            subPath: datasource.yaml
          - mountPath: /etc/grafana/provisioning/dashboards/dashboards.yaml
            name: grafana-config
            subPath: dashboards.yaml
          - mountPath: /var/lib/grafana/dashboards
            name: dashboard-config

      volumes:
        - name: grafana-config
          configMap:
            defaultMode: 420
            name: grafana-config
        - name: dashboard-config
          configMap:
            defaultMode: 420
            name: dashboard-config
