apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9090'
      service.beta.kubernetes.io/aws-load-balancer-type: external
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
      service.beta.kubernetes.io/aws-load-balancer-scheme: internal
      external-dns.alpha.kubernetes.io/hostname: qa-influxdb-dev.infuratest.io
spec:
  selector:
    app: influxdb
  type: NodePort
  ports:
    - port: 8086
      targetPort: 8086
  type: LoadBalancer
  selector:
    app: influxdb
