apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9090'

spec:
  selector:
    app: influxdb
  type: NodePort
  ports:
    - port: 8086
      targetPort: 8086
