apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  namespace: harmony
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9090'

spec:
  selector:
    app: influxdb
  type: NodePort
  ports:
    - port: 8086
      targetPort: 8086
      nodePort: 31000
