apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: k6-worker-logs
  labels:
    app: k6-worker-logs
spec:
  serviceName: k6-worker-logs
  replicas: 1
  selector:
    matchLabels:
      app: k6-worker-logs
  template:
    metadata:
      labels:
        app: k6-worker-logs
    spec:
      containers:
        - name: k6
          image: registry.gitlab.com/jasonyihk/docker/k6:prom
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              apk add curl &&
              curl https://gist.githubusercontent.com/lorenzourb/cbdaf76022dc984a53d56f1d794a6cd1/raw/9b6f23d94ff877821d0387c5dd5fbc20a0fde25c/data-consistency-logs-monitor.js --output test.js &&
              export INFURA_ID="06c059d611c641ffac588230c08f2e6c" && export ALCHEMY_ID="jN1FmmT5hBDoTDJTK9fZG0B2tM0ZsR0h" &&
              K6_INFLUXDB_PUSH_INTERVAL=2s k6 run --out influxdb="http://influxdb-service:8086/myk6db" test.js -e env=prod >> ./output.txt
            # - |
            #
          ports:
            - containerPort: 3000
              name: notused
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
          resources:
            limits:
              cpu: '4'
              memory: 16Gi
            requests:
              cpu: '1'
              memory: 1Gi
